# -*- coding: utf-8 -*-
"""Chaining_methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w4Oh3BUa69ZGzMnZjHEzTzTpoL5ai-rW
"""

import numpy as np
import pandas as pd

"""**Before Chaining Methods**

"""

# Load Data
df = pd.read_csv("/content/FAOSTAT_data_en_3-29-2026.csv")

# Step 1: Clean names
df.columns = [x.strip().lower().replace(' ', '_') for x in df.columns]
df

# Step 2: Filter zeros (In-place or reassignment)
df = df[df['value'] > 0]

df

# Step 3: Pivot the table
df_wide = df.pivot_table(index=['area', 'item', 'year'],
                         columns='element',
                         values='value').reset_index()

df_wide

# Step 4: Rename for math
df_wide = df_wide.rename(columns={'Production': 'prod', 'Area harvested': 'area_h'})

df_wide

# Step 5: Calculate Median (This requires a separate variable)
median_stats = df.groupby(['area', 'item'])['value'].median().reset_index()
median_stats.columns = ['area', 'item', 'median_val']

median_stats

# Step 6: Merge
df_final = pd.merge(df_wide, median_stats, on=['area', 'item'], how='left')

df_final

# Step 7: Final Math
df_final['area_h'] = df_final['area_h'].fillna(df_final['median_val'])
df_final['yield'] = df_final['prod'] / df_final['area_h']

print(df_final.head())





"""**After Chaining Methods**"""

import pandas as pd
import numpy as np

# THE PRO PIPELINE
df_agri = (
    pd.read_csv("/content/FAOSTAT_data_en_3-29-2026.csv")

    # 1. Standardize (Vectorized)
    .rename(columns=lambda x: x.strip().lower().replace(' ', '_'))

    # 2. Filter early to save memory
    .query("value > 0")

    # 3. Reshape (Long to Wide)
    .pivot_table(index=['area', 'item', 'year'],
                 columns='element',
                 values='value')
    .reset_index()
    .rename(columns={'Production': 'prod', 'Area harvested': 'area_h'})

    # 4. Self-Merge (Using a lambda to reference the 'living' dataframe)
    .merge(
        (pd.read_csv("/content/FAOSTAT_data_en_3-29-2026.csv")
         .groupby(['Area', 'Item'])['Value'].median().reset_index()
         .rename(columns={'Area': 'area', 'Item': 'item', 'Value': 'med_area'})),
        on=['area', 'item'],
        how='left'
    )

    # 5. Final Mathematical Transformation
    .assign(
        area_h = lambda x: x['area_h'].fillna(x['med_area']),
        calc_yield = lambda x: (x['prod'] / x['area_h']).replace([np.inf, -np.inf], 0)
    )

    # 6. Logical Filter
    .loc[lambda x: x['calc_yield'] > 0]
)

print(df_agri.head())

